version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 1,15 * *" # twice a month, closest dependabot gets to every two weeks
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 1,15 * *" # twice a month, closest dependabot gets to every two weeks
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      python-deps:
        patterns:
          - "*"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 1,15 * *" # twice a month, closest dependabot gets to every two weeks
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      pre-commit:
        patterns:
          - "*"
