# Core Labels
- name: "bug"
  description: "Something is not working"
  color: "ff0000"

- name: "feature"
  description: "New feature or request"
  color: "28a745"

- name: "enhancement"
  description: "Improvement to existing functionality"
  color: "17a2b8"

- name: "docs"
  description: "Documentation updates"
  color: "1f77b4"

# Infrastructure & Deployment
- name: "infrastructure"
  description: "Infrastructure configuration changes"
  color: "264653"

- name: "deployment"
  description: "Deployment automation changes"
  color: "6f42c1"

- name: "server-config"
  description: "Server configuration updates"
  color: "ff9500"

- name: "security"
  description: "Security-related changes"
  color: "ee0701"

# Status Labels
- name: "needs review"
  description: "Pull request needs code review"
  color: "fbca04"

- name: "ready to merge"
  description: "Pull request is approved and ready to merge"
  color: "0e8a16"

- name: "in progress"
  description: "Work is currently in progress"
  color: "ededed"

# Priority Labels
- name: "priority: high"
  description: "High priority issue or PR"
  color: "d93f0b"

- name: "priority: medium"
  description: "Medium priority issue or PR"
  color: "fbca04"

- name: "priority: low"
  description: "Low priority issue or PR"
  color: "0e8a16"

# Other Labels
- name: "dependencies"
  description: "Changes to dependencies"
  color: "a569bd"

- name: "release-note-none"
  description: "No release note"
  color: "5dade2"
