default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args:
          [
            --explicit-package-bases,
            --namespace-packages,
            --ignore-missing-imports,
          ]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.11.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.4
    hooks:
      - id: uv-lock

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
